spring:
  application:
    name: ringdu-server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ringdu}
    username: ${DB_USERNAME:ringdu}
    password: ${DB_PASSWORD:ringdu1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
